title: Rafael Ferreira da Silva, Ph.D. - Senior Research Scientist
description: 'Senior Research Scientist at the Oak Ridge National Laboratory. Research: Modeling and Simulation of parallel and distributed computing systems; Scientific Workflows scheduling, optimization, fault-tolerance, and energy-efficiency; and Distributed Computing on clouds, grids, and HPC clusters.'
url: https://rafaelsilva.com

markdown: kramdown
enable-mathjax: yes

permalink: /blog/:title/

# Pagination
paginate: 8
paginate_path: /blog/page:num/

include:
  - _pages

# Google Ananlytics Tracker.
analytics: UA-338939-1

# scholar
scholar:
  sort_by: author
  group_by: year
  group_order: descending
  type_order: [article, inproceedings, phdthesis, techreport]
  bibliography_template: bib

collections:
  presentations:
    output: true
    permalink: /publications/presentations/:path/
  projects:
    output: true
    permalink: /projects/:path/

exclude:
  - .git
  - .github
  - .idea
  - .jekyll-cache

plugins:
  - jekyll-sitemap    # Adds sitemap to the website at /sitemap.xml
  - jekyll-feed       # Adds feed to the website at /feed.xml
  - jekyll-paginate   # Used for sorting posts by page numbers.
  - jekyll-seo-tag    # Adds all the important SEO meta tags by default.
  - jekyll-scholar
